### ISSUE TITLE
Section titles

### ISSUE THREAD

**Issue by DavidHaslam** [krisek/HunKar#10]
Please refer to [Marking pre-verse titles](https://wiki.crosswire.org/OSIS_Bibles#Marking_pre-verse_titles)

> There is no special markup for pre-verse titles. **Osis2mod** will determine what titles belong to the book, the chapter and otherwise if the above advice is followed.

This means that you may omit ` subType="x-preverse"` in each such **title** element.

**Comment by krisek** [comment]
I remember back in 200x some clients still needed this attribute to render the section title correctly. If it doesn't hurt I'd really like to leave it in.

**Comment by DavidHaslam** [comment]
No - these are superfluous and should be removed. 

**osis2mod** now places all preverse content in a **div** element, e.g.
```
$$$Genesis 1:1
<div type="x-milestone" subType="x-preverse" sID="pv1"/><div sID="gen4" type="section"/><title subType="x-preverse">A világ teremtése</title> <div type="x-milestone" subType="x-preverse" eID="pv1"/>Kezdetben teremté Isten az eget és a földet. <note n="4d" osisID="Gen.1.1!crossReference.4d" osisRef="Gen.1.1" type="crossReference"><reference osisRef="Gen.2.4">1Móz 2,4.5</reference> <reference osisRef="Ps.33.6">Zsolt 33,6</reference> <reference osisRef="Ps.89.12">Zsolt 89,12</reference> <reference osisRef="Ps.136.5">Zsolt 136,5</reference> <reference osisRef="Acts.14.15">Csel 14,15</reference> <reference osisRef="Acts.17.24">Csel 17,24</reference> <reference osisRef="Heb.11.3">Zsid 11,3</reference> <reference osisRef="Job.33.4">Jób 33,4</reference> </note>
```

The first part is
```
<div type="x-milestone" subType="x-preverse" sID="pv1"/><div sID="gen4" type="section"/><title subType="x-preverse">A világ teremtése</title> <div type="x-milestone" subType="x-preverse" eID="pv1"/>
```
As you can see, the attribute `subType="x-preverse"` is found in the milestone form of the **div** element generated during module build. Repeating the same attribute in the **title** element does not help, and may even hinder the display.

**Comment by DavidHaslam** [comment]
I just rebuilt the module with `-v Calvin` after the following changes to the XML file:
1. Removed all ` subType="x-preverse"` from the **title** elements.
2. Changed to `<refSystem>Bible.Calvin</refSystem>` in lines 14, 17.

I confirm that **Xiphos** now displays all the section titles correctly.

See [screenshot](https://www.dropbox.com/s/twz7jff0cwq40af/Screenshot%202020-08-25%2016.38.18.png?dl=0).

I am pretty sure that the improvement was due to the _systematic change_ to the **title** elements.

**Comment by krisek** [comment]
fixed in cec31cf

**Comment by DavidHaslam** [comment]
@krisek 

The removal of the superfluous attributes was incomplete! Eight instances still remain in the **Song of Songs**.
```
<div type="section"><title subType="x-preverse">A Vőlegény és Menyasszon benső szerelme</title>
<div type="section"><title subType="x-preverse">A Menyasszony vágyódása a Vőlegényhez</title>
<div type="section"><title subType="x-preverse">A Menyasszony hűsége</title>
<div type="section"><title subType="x-preverse">A Menyasszony jelességei</title>
<div type="section"><title subType="x-preverse">A Menyasszony hallja a Vőlegény szavát, panaszolja tőle való elválasztatását és dicséri szépségét</title>
<div type="section"><title subType="x-preverse">Az újra egyesülés öröme</title>
<div type="section"><title subType="x-preverse">A Vőlegény és Menyasszony párbeszéde</title>
<div type="section"><title subType="x-preverse">Az örökre egyesültek hűsége</title>
```

**Comment by krisek** [comment]
Guess why there here... Song of Solomon is imported from a static file, I'll fix it with the next release.
