### ISSUE TITLE
Improper osisRef strings in the XML file

### ISSUE THREAD

**Issue by DavidHaslam** [krisek/HunKar#11]
In the XML file, there are 2114 matches to the regex `.">` 

Here's one example to illustrate the problem:
```
              <verse osisID="Rev.1.2">A ki bizonyságot tett az Isten beszédéről és Jézus Krisztus bizonyságtételéről, mindenről, a mit látott. <note osisID="Rev.1.2!crossReference.d0" n="d0" osisRef="Rev.1.2" type="crossReference"><reference osisRef="2Cor.5.3">2Kor 5,3</reference> <reference osisRef="2Cor.">2Kor </reference> </note></verse>
```

The second reference is `<reference osisRef="2Cor.">2Kor </reference>` which seems to be an improper reference to a whole book.

A cross-reference to a whole book should be very rare even in a study Bible, so my guess is that this is an artefact of a scripting error.

In each case, the referenced whole book is is the same book as used in the preceding proper reference to a limited number of verses, often only the one.

**Comment by krisek** [comment]
fixed with 6ac5d63

![image](https://user-images.githubusercontent.com/786044/91898836-a2497d80-ec9c-11ea-87e5-6861ddc14096.png)
