### ISSUE TITLE
Change path for osisCore.2.1.1.xsd

### ISSUE THREAD

**Issue by DavidHaslam** [krisek/HunKar#13]
The **bibletechnologies.net** website ceased to exist some years back.

Line 6 in the file `hunkaroli_rev.osis.xml` could be sensibly changed to
```
        xsi:schemaLocation="http://www.bibletechnologies.net/2003/OSIS/namespace https://www.crosswire.org/osis/osisCore.2.1.1.xsd">
```
This enables validation from within text editors such as **Notepad++** via the **XMLTools** plugin.

See also [HunUj issue 4](https://github.com/krisek/HunUj/issues/4)

**Comment by krisek** [comment]
fixed in 33472c5
