### ISSUE TITLE
GlobalOptionFilter keys missing from hunkar.conf

### ISSUE THREAD

**Issue by DavidHaslam** [krisek/HunKar#2]
The .conf file did not include either of the following lines:
```
GlobalOptionFilter=OSISHeadings
GlobalOptionFilter=OSISFootnotes
GlobalOptionFilter=OSISScripref
```
These are required for supporting the features in the OSIS source file.

Here's a Zip file containing my edited version.

[hunkar.zip](https://github.com/krisek/HunKar/files/5057968/hunkar.zip)

NB. I first  re-ordered the lines in the .conf file.

**Comment by krisek** [comment]
fixed with 0c267ee
