### ISSUE TITLE
Significant whitespace omissions

### ISSUE THREAD

**Issue by DavidHaslam** [krisek/HunKar#3]
The **diatheke** output of the module with **plain** text format and no output options has many instances of a **punctuation mark** being followed immediately by a new word _without any space_ in between.

There are instances of this type for `(period|comma|colon|semicolon|question mark|exclamation mark)`.

The root cause is likely to be that **significant whitespace** was inadvertently _omitted_ in the XML file, a fact obscured perhaps by the presence of **note** elements, etc in these locations.

To help you get a handle on this, I have uploaded a Zip file containing this file.

[HunKar.diatheke.txt.zip](https://github.com/krisek/HunKar/files/5059050/HunKar.diatheke.txt.zip)

NB. It will be easier to find the instances involving a `colon` in verse text if these are _first removed_ from the `chapter:verse:` references for all 31102 verses of the text file. i.e. Replace all `(\d+):(\d+):` by `$1~$2~`. 

This would then facilitate a simpler regular expression `[\.,;:\?\]\w+` being used to search for the **662** instances of a missing space.

Less worrying are the **13673** instances of **multiple whitespace** and 3035 lines with **blanks at EOL** in the same output file, though it would be nice to fix these too,

**Comment by krisek** [comment]
The origin text was pretty low quality from this perspective. I implemented fixes (punctuation mark being followed immediately by a new word without any space in between, blanks at EOL) in b8fe5b3, I hope it didn't break anything else. Multiple whitespace shouldn't be an issue XML should merge those into one.

**Comment by krisek** [comment]
Should be fixed with the new source.
