### ISSUE TITLE
Truncated verses and a missing book!

### ISSUE THREAD

**Issue by DavidHaslam** [krisek/HunKar#8]
Comparing the **diatheke** output of the updated module with the **diatheke** output from 2011 shows that there are numerous verses in which the verse text has been truncated, In most such locations, the second sentence is completely missing!

- Judges 5:2-31
- Judges 14:14, 18, 15:16
- I Samuel 2:1-10
- II Samuel 22:3-23, 25-51
- Nehemiah 1:1
- Psalms 15:1, 16:1, 17:1, 23:1, 24:1, 25:1, 26:1, 27:1,  ... 150:1
- Proverbs 10:1
- Isaiah 15:1, 19:1, 21:1, 22:1, 23:1

The whole of the **Song of Solomon** is missing from the XML file!
```
    <div osisID="Song" type="book">
      
    </div> <!-- end book Song //-->
```

**Comment by DavidHaslam** [comment]
The attached Zip file contains the **WinMerge** patch that documents the issues outlined above.

[HunKar.diatheke.diff.zip](https://github.com/krisek/HunKar/files/5112256/HunKar.diatheke.diff.zip)

NB. There are few diffs that are already mentioned elsewhere in #5

**Comment by DavidHaslam** [comment]
**Judges 5** at [BIRÁK KÖNYVE 5. fejezet](https://abibliamindenkie.hu/karoli/JDG/5/) does not have any truncated verse text, so it must be that your script failed to capture it fully. _The other truncation locations probably have the same cause_.

The **Song of Songs** is certainly available at [ÉNEKEK ÉNEKE](https://abibliamindenkie.hu/karoli/SNG/) so it must be that your  script failed to capture it at all.

**Comment by DavidHaslam** [comment]
This issue may be closed.

**Comment by DavidHaslam** [comment]
@krisek 

FYI. The inaccessibility of **Song of Songs** in the TextSource [website](https://szentiras.hu/KG) is reported [here](https://github.com/borazslo/szentiras.hu/issues/134) in the related GitHub [repo](https://github.com/borazslo/szentiras.hu).

_Please watch that repo and plan to use the consistent source once the maintainers have fixed the bug_,

Understand that using [ÉNEKEK ÉNEKE](https://abibliamindenkie.hu/karoli/SNG/) is only a **provisional workaround** until then.

Please make the status fully transparent in the README file.

**Comment by krisek** [comment]
I'm already in touch with the developers of szentiras.hu in e-mail.

Readme added in fb3df60
